# Generated by Django 3.1.6 on 2021-02-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='additions',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='changes',
            name='old_state',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='changes',
            name='removals',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='changes',
            name='updates',
            field=models.JSONField(blank=True),
        ),
    ]
