# Generated by Django 3.1.6 on 2021-03-12 11:44

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('content', django_quill.fields.QuillField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('recipients', models.ManyToManyField(blank=True, to='contacts.Contact')),
            ],
        ),
    ]
