# Generated by Django 3.1.6 on 2021-03-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=100, verbose_name='Asunto del mensaje')),
                ('content', models.TextField(blank=True, default='', verbose_name='Contenido del mensaje')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('recipients', models.ManyToManyField(to='contacts.Contact')),
            ],
        ),
    ]
