# Generated by Django 3.1.6 on 2021-02-28 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailtemplates', '0002_auto_20210228_0122'),
        ('agendas', '0005_auto_20210227_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.agenda')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailtemplates.template')),
            ],
        ),
    ]
