# Generated by Django 3.1.6 on 2021-03-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('mailsender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massmail',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='massmail',
            name='recipients',
            field=models.ManyToManyField(to='contacts.Contact'),
        ),
    ]
