# Generated by Django 3.1.7 on 2021-04-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210421_0245'),
        ('mailsender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massmail',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Cuerpo'),
        ),
        migrations.AlterField(
            model_name='massmail',
            name='recipients',
            field=models.ManyToManyField(to='contacts.Contact', verbose_name='Destinatarios'),
        ),
        migrations.AlterField(
            model_name='massmail',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Asunto'),
        ),
    ]
