# Generated by Django 4.2.1 on 2023-07-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0003_resultadodifusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massmail',
            name='subject',
            field=models.TextField(blank=True, default='', verbose_name='Asunto'),
        ),
    ]
