# Generated by Django 2.2.7 on 2021-02-02 05:50

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('contact_info', jsonfield.fields.JSONField(default='{}')),
                ('agenda', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agendas.Agenda')),
            ],
            options={
                'unique_together': {('email', 'agenda')},
            },
        ),
    ]
