# Generated by Django 3.1.7 on 2021-04-21 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_auto_20210421_0245'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.agenda', verbose_name='Agenda asociada'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_info',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Información del contacto'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email del contacto'),
        ),
    ]
