# Generated by Django 3.1.6 on 2021-02-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210221_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
