# Generated by Django 2.2.7 on 2021-02-02 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=199)),
                ('description', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(unique=True, verbose_name='')),
                ('year', models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(9999)])),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
