# Generated by Django 3.1.7 on 2021-04-21 02:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agendas.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Slug de la agenda (URL amigable)'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='title',
            field=models.CharField(default='', max_length=199, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(9999)], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(verbose_name='Slug de la categoria (URL amigable)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
