# Generated by Django 2.2.7 on 2021-02-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
