# Generated by Django 2.2.7 on 2021-01-17 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 9, 9, 2, 430284, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='title',
            field=models.CharField(default='', max_length=199),
            preserve_default=False,
        ),
    ]
