# Generated by Django 2.2.7 on 2021-02-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_auto_20210203_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='description',
            field=models.TextField(blank=True, default='', max_length=199),
        ),
    ]
