# Generated by Django 2.2.7 on 2021-02-02 03:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_auto_20210202_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='title',
        ),
        migrations.AddField(
            model_name='agenda',
            name='Year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='agenda',
            name='name',
            field=models.CharField(default='', max_length=199),
        ),
    ]
