# Generated by Django 2.2.7 on 2021-02-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_auto_20210202_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='description',
        ),
    ]
