# Generated by Django 2.2.7 on 2021-02-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0005_remove_agenda_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='name',
            new_name='title',
        ),
    ]
