# Generated by Django 3.1.8 on 2023-01-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0005_auto_20230129_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='URL amigable'),
        ),
    ]
