# Generated by Django 2.2.7 on 2021-02-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0006_auto_20210202_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
