# Generated by Django 2.2.7 on 2021-02-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0007_agenda_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
