# Generated by Django 2.2.7 on 2021-02-02 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0008_auto_20210202_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='Year',
            new_name='year',
        ),
    ]
