# Generated by Django 3.1.6 on 2021-03-12 11:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default='', unique=True)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('content', django_quill.fields.QuillField()),
                ('year', models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(9999)])),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailtemplates.category')),
            ],
        ),
    ]
