# Generated by Django 3.1.7 on 2021-04-21 02:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailtemplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(verbose_name='Slug de la categoría (URL amigable)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailtemplates.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Cuerpo del mensaje'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Slug de la plantilla (URL amigable)'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Asunto del mensaje'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(9999)], verbose_name='Año'),
        ),
    ]
