# Generated by Django 3.1.6 on 2021-02-27 23:22

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailtemplates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, default='', max_length=199),
        ),
        migrations.AddField(
            model_name='template',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='template',
            name='year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
