# Generated by Django 3.1.6 on 2021-03-01 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0001_initial'),
        ('mailtemplates', '0002_auto_20210228_0122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template',
            new_name='MailTemplate',
        ),
    ]
