# Generated by Django 3.1.6 on 2021-03-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailtemplates', '0002_auto_20210312_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
