version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
       - ./.env
  agenda:
    build: ./src/
    image: gabcas28/mobility-agenda
    restart: always
    depends_on:
      - db
    command:  bash -c " invoke install && invoke start"    
    volumes:
      - ./src:/src
      - static_volume:/home/agenda/static
      - media_volume:/home/agenda/media
    expose:
      - 8000
    env_file:
      - ./.env

  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - agenda
    volumes:
      - static_volume:/home/agenda/static
      - media_volume:/home/agenda/media
volumes:
  postgres:
  static_volume:
  media_volume: